{
    'name': 'Marley CRM Enhancements',
    'version': '19.0.1.3.0',
    'summary': 'CRM lifecycle stages, Won/Loss logic, quotation from lead, project creation',
    'description': 'Implements Marley Fans CRM requirements: stage data, Won conversion to Customer + Project, Loss enforcement with mandatory remarks, Won notifications, and quotation creation from leads.',
    'category': 'Sales/CRM',
    'author': 'Techmatic Systems',
    'website': 'https://www.techmaticsys.com',
    'depends': [
        'crm',
        'mail',
        'sale_management',
        'sale_crm',
        'sale_project',
        'project',
        'crm_lead_automation_engine',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/order_booking_task_rules.xml',
        'data/crm_stages.xml',
        'data/crm_lost_reasons.xml',
        'data/project_stages.xml',
        'data/sales_project_access.xml',
        'report/installation_report.xml',
        'report/installation_template.xml',
        'report/installation_task_report.xml',
        'report/installation_task_template.xml',
        'data/email_template_installation.xml',
        'data/sale_template_override.xml',
        'views/crm_lead_views.xml',
        'views/project_views.xml',
        'views/project_task_views.xml',
        'wizard/crm_lead_lost_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'marley_crm_enhancements/static/src/js/chatter_send_message_restrict.js',
            'marley_crm_enhancements/static/src/xml/chatter_send_message_restrict.xml',
            'marley_crm_enhancements/static/src/js/message_edit_delete_restrict.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'maintainer': 'Techmatic Odoo Team',
    'support': 'info@techmaticsys.com',
}
