from . import business_city
from . import business_area
from . import automation_service
from . import res_partner
from . import crm_lead
from . import whatsapp_bulk_wizard
from . import auto_email
from . import auto_whatsapp
from . import crm_email_log
from . import res_config_settings
