{
    'name': 'Marley Sale Reports',
    'version': '19.0.1.3.0',
    'summary': 'Custom Quotation and Proforma Invoice print layouts for Marley Fans',
    'description': 'QWeb report templates matching Marley Fans branding: Quotation with technical specs and commercial terms, Proforma Invoice. Delivery Note will be added once the stock module is available.',
    'category': 'Sales',
    'author': 'Techmatic Systems',
    'website': 'https://www.techmaticsys.com',
    'depends': [
        'sale_management',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'report/quotation_report.xml',
        'report/quotation_template.xml',
        'report/proforma_invoice_report.xml',
        'report/proforma_invoice_template.xml',
        'report/invoice_document_override.xml',
        'report/quotation_document_override.xml',
        'data/gst_fiscal_positions.xml',
        'data/mail_template_override.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/product_template_views.xml',
    ],
    'post_init_hook': '_post_init_swap_quotation_report',
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'maintainer': 'Techmatic Odoo Team',
    'support': 'info@techmaticsys.com',
}
